services:
  backrest-config-backup:
    container_name: backrest-config-backup
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    secrets:
      - source: age_passphrase
        target: /age_passphrase.txt
    volumes:
      - ./config.json:/data/config.json:ro
    restart: no

secrets:
  age_passphrase:

    file: ./age_passphrase.txt
