services:
  backrest-config-backup:
    container_name: backrest-config-backup
    image: ghcr.io/frostwalk/backrest-config-backup:latest
    env_file: secrets.env
    secrets:
      - source: passphrase
        target: /age_passphrase.txt
    volumes:
      - config.json:/data/config.json:ro
    restart: unless-stopped

secrets:
  passphrase:
    file: ./age_passphrase.txt